name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'

    - run: ./bin/update-gh-pages
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

