name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - run: |
      curl -OL https://github.com/andre2007/d-tips-generator/releases/download/v1.0.0/dtg-1.0.0-linux-x86_64.tar.xz
      tar -xf dtg-1.0.0-linux-x86_64.tar.xz
      ./dtg

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'

    - run: ./bin/update-gh-pages
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

